spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/babaykakeeper
    username: babayka_user
    password: babayka_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    pr.vexor.telegrambot.babaykakeeper: DEBUG
    org.hibernate.SQL: DEBUG
    
app:
  instance:
    name: ${INSTANCE_NAME:home-pc}
    activity-flag-filename: ${ACTIVITY_FLAG_FILENAME:C:\\\\Windows\\Temp\\babayka_bot_active.flag}

telegram:
  bot:
    token: ${BOT_TOKEN}
    name: ${BOT_NAME}
  owner-id: ${OWNER_ID}
  channel-id: ${CHANNEL_ID}
  private-group:
    id: ${PRIVATE_GROUP_ID}
    text: ${PRIVATE_GROUP_TEXT:-ntrcn}
